In [1]:
import functions

In [3]:
functions.get_counts_table('brca')

                 Unnamed: 1  gain  neutral  loss
7SK       ENSG00000232512.2    15       89    18
7SK       ENSG00000249352.3    11       80    31
7SK       ENSG00000254144.2    66       49     7
7SK       ENSG00000260682.2     9       50    63
7SK       ENSG00000271765.1    13       86    23
...                     ...   ...      ...   ...
snoZ6     ENSG00000252200.1    12       93    17
snoZ6     ENSG00000253067.1     9       89    24
snoZ6     ENSG00000264452.1    21       86    15
snoZ6     ENSG00000266692.1    21       86    15
snosnR66  ENSG00000212397.1     5       69    48

[23692 rows x 4 columns]